# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeServerlessBoilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeServerlessBoilerplate

  # Firebase
  pod 'Firebase/AdMob', '~> 5.9.0'
  pod 'Firebase/Firestore', '~> 5.9.0'
  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'Firebase/Database', '~> 5.9.0'
  pod 'Firebase/RemoteConfig', '~> 5.9.0'
  pod 'Firebase/Storage', '~> 5.9.0'
  pod 'Firebase/Performance', '~> 5.9.0'


  target 'ReactNativeServerlessBoilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeServerlessBoilerplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeServerlessBoilerplate-tvOS

  target 'ReactNativeServerlessBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
