# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EMBPRNFirebaseBoilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EMBPRNFirebaseBoilerplate

  # Firebase
  pod 'Firebase/AdMob', '~> 5.9.0'
  pod 'Firebase/Firestore', '~> 5.9.0'
  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'Firebase/Database', '~> 5.9.0'
  pod 'Firebase/RemoteConfig', '~> 5.9.0'
  pod 'Firebase/Storage', '~> 5.9.0'
  pod 'Firebase/Performance', '~> 5.9.0'
  
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-sensitive-info', :path => '../node_modules/react-native-sensitive-info'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'EMBPRNFirebaseBoilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EMBPRNFirebaseBoilerplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EMBPRNFirebaseBoilerplate-tvOS

  target 'EMBPRNFirebaseBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
